version: "3.7"

services:
  webapp:
    image: node:18-alpine
    container_name: app
    working_dir: /app
    volumes:
      - ./:/app
    command: "npm start"
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
