# This is a basic workflow to help you get started with Actions

name: Node.js CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install RSYNC
        run: sudo apt-get install rsync

      - name: Deploy to VDS
        env:
          REMOTE_HOST: cu04179@92.53.106.114
        run: |
          rsync -avzhe "ssh -o StrictHostKeyChecking=no" ./ $REMOTE_HOST --exclude '.git'
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      # ssh-keyscan -H cu04179@92.53.106.114 >> ~/.ssh/known_hosts
      - name: ssh
        run: ssh -i ~/.ssh/id_rsa -v cu04179@92.53.106.114
