# This is a basic workflow to help you get started with Actions

name: Node.js CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDmvWlszq4Rny7tRuC3mDGDte+ct6+9wlT235zWVoLra584DiHhTqwyZYT72NJHv1CLWNaS0FduEj0gHOtk4Zk5iDOJ1wF3/0IumF32MP7rTwSFUa2dqLsijpjwgaZG+Hhx4VILOS87T2JCHx6221jGl2BXu56xnhGNmrAguSPOIyOvYk73EmjqjHn+3v0JrI/zwgTCleC3Vh78y5yzpF6HKcZAlx6pJTyuriCNrydIyNJI/rZVmdliu3Jp5FrIdNJVkFtKfCYWSCbq2uVTKRM8V6xgnqLWZLzdQ9PyyH4rwL58df+eF6sg9lT+GAfC+ofivPv6uGTRXE1JnTiiLj9rLJ0aMNE1VUZsWkhvCoKd+JFt3NE7Xb1qOwUIOgKdRsUkPoDKtfJWnxky9XEudEH9X6wc7aExp0d5IQfDBPWbMGSwhkVhrkFWu+7GMa8JIq98KoTkBaUIWQWBC0RI1JVpYhwEr4PFpiy9Oe4wtld38Og4oQk3YTXCtyVQNFGAqkvUUNtR0KYHJfhhirtfHFBQ6tYYqenlqFSr3g3hlXzFN2W+YNwX4qG5eoph7U7o5G0BDvwHNTwbO/NHNKaItjQrihHH8DY+/8gLGYaBVyl2ho8Liy8kne70h67ac5iYiVTSDY0udIqqJUrIB4aaZDHpkVUDT/lsLOkMGuGjb0r9dw== boumrz@gmail.com

      - name: Install RSYNC
        run: sudo apt-get install rsync

      - name: Deploy to VDS d
        env:
          REMOTE_HOST: cu04179@92.53.106.114
        run: |
          rsync -avzhe "ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60" ./ cu04179@92.53.106.114:public_html --exclude '.git'
